import annapurnaImg from "@/assets/reels/annapurna.jpg";
import everestImg from "@/assets/reels/everest.jpg";
import langtangImg from "@/assets/reels/langtang.jpg";
import mustangImg from "@/assets/reels/mustang.jpg";
import poonhillImg from "@/assets/reels/poonhill.jpg";
import koiliBusImg from "@/assets/services/koili-bus.png";
import swiftHolidayBusImg from "@/assets/services/swift-holiday-bus.png";
import hotelMountainTopImg from "@/assets/services/hotel-mountain-top.png";
import cindermintCafeImg from "@/assets/services/cindermint-cafe.png";
import tropicanaCafeImg from "@/assets/services/tropicana-cafe-v2.png";

import { createSampleTrip } from "@/components/trip-upload/data";
import type { ServiceMarketplaceCard, ServiceMarketplaceSectionData } from "@/components/services/types";

const trip = createSampleTrip();

const hotelFeatured: ServiceMarketplaceCard = {
  id: "hotel-mountain-top",
  category: "Hotels",
  filterGroup: "hotels",
  title: "Hotel Mountain Top",
  subtitle: "Featured stay from your trip",
  location: "Pokhara Lakeside",
  price: "Rs 3,250",
  numericPrice: 3250,
  description: "Your stay from the Pokhara New Year 2083 trip with a clean night-by-night cost summary and budget-friendly lakeside positioning.",
  rating: 4.5,
  tags: ["Lakeside", "Budget Stay", "Mountain View"],
  ctaPrimary: "View Stay Details",
  ctaSecondary: "Visit",
  image: hotelMountainTopImg,
};

const hotelRecommendations: ServiceMarketplaceCard[] = [
  {
    id: "hotel-lake-breeze",
    category: "Hotels",
    filterGroup: "hotels",
    title: "Hotel Lake Breeze",
    subtitle: "Recommended alternative",
    location: "Pokhara Lakeside",
    price: "From Rs 3,400",
    numericPrice: 3400,
    description: "A bright lakeside stay with balcony views and an easy walk to cafes, nightlife, and the lakefront.",
    rating: 4.6,
    tags: ["Breakfast", "Lakeside", "Balcony"],
    ctaPrimary: "View Details",
    ctaSecondary: "Visit",
    image: tropicanaCafeImg,
  },
  {
    id: "hotel-himalayan-view",
    category: "Hotels",
    filterGroup: "hotels",
    title: "Himalayan View Inn",
    subtitle: "Recommended alternative",
    location: "Pokhara Lakeside",
    price: "From Rs 2,900",
    numericPrice: 2900,
    description: "A softer-budget stay that still keeps mountain-facing rooms and easy taxi access for your itinerary.",
    rating: 4.4,
    tags: ["Budget", "Mountain View", "Quiet"],
    ctaPrimary: "View Details",
    ctaSecondary: "Visit",
    image: cindermintCafeImg,
  },
  {
    id: "hotel-lakeside-retreat",
    category: "Hotels",
    filterGroup: "hotels",
    title: "Pokhara Lakeside Retreat",
    subtitle: "Recommended alternative",
    location: "Pokhara Lakeside",
    price: "From Rs 4,100",
    numericPrice: 4100,
    description: "A slightly more premium retreat with stronger interiors, rooftop breakfast, and a polished travel-app feel.",
    rating: 4.7,
    tags: ["Rooftop", "Modern", "Couple Friendly"],
    ctaPrimary: "View Details",
    ctaSecondary: "Visit",
    image: everestImg,
  },
];

const foodCards: ServiceMarketplaceCard[] = [
  {
    id: "food-tropicana",
    category: "Cafes & Restaurants",
    filterGroup: "food",
    title: "Tropicana Cafe",
    subtitle: "Cafe",
    location: "Begnas Lake, Pokhara",
    price: "Spent Rs 375",
    numericPrice: 375,
    description: "A laid-back cafe stop from your lakeside-to-Begnas day, ideal for a relaxed drink and scenic break.",
    rating: 4.4,
    tags: ["Cafe", "Begnas", "Scenic"],
    ctaPrimary: "Visit",
    image: annapurnaImg,
  },
  {
    id: "food-tipsy-tuna",
    category: "Cafes & Restaurants",
    filterGroup: "food",
    title: "Tipsy Tuna Cafe",
    subtitle: "New Year Eve Cafe",
    location: "Lakeside, Pokhara",
    price: "Spent Rs 1,250",
    numericPrice: 1250,
    description: "Your New Year Eve spot with party energy, music, and a more premium spend from the itinerary.",
    rating: 4.8,
    tags: ["Party", "Music", "Lakeside"],
    ctaPrimary: "Visit",
    image: poonhillImg,
  },
  {
    id: "food-cindermint",
    category: "Cafes & Restaurants",
    filterGroup: "food",
    title: "Cindermint Cafe",
    subtitle: "Cafe",
    location: "Pokhara Lakeside",
    price: "Spent Rs 500",
    numericPrice: 500,
    description: "A cafe breakfast stop from your Tuesday itinerary with a slower morning tone before kayaking.",
    rating: 4.6,
    tags: ["Breakfast", "Cafe", "Lakeside"],
    ctaPrimary: "Visit",
    image: langtangImg,
  },
  {
    id: "food-wings-momo",
    category: "Cafes & Restaurants",
    filterGroup: "food",
    title: "Wings Momo",
    subtitle: "Local Food",
    location: "Lakeside, Pokhara",
    price: "Spent Rs 450",
    numericPrice: 450,
    description: "A casual momo stop from your roam-around-Lakeside day with easy local comfort food.",
    rating: 4.5,
    tags: ["Local Food", "Momo", "Casual"],
    ctaPrimary: "Visit",
    image: mustangImg,
  },
  {
    id: "food-mantra-thakali",
    category: "Cafes & Restaurants",
    filterGroup: "food",
    title: "Mantra Thakali",
    subtitle: "Restaurant",
    location: "Pokhara, Nepal",
    price: "Spent Rs 690",
    numericPrice: 690,
    description: "A fuller Thakali meal stop that fits the dinner slot in your Tuesday spending history.",
    rating: 4.7,
    tags: ["Thakali", "Dinner", "Local Favorite"],
    ctaPrimary: "Visit",
    image: everestImg,
  },
  {
    id: "food-kurintar-retreat",
    category: "Cafes & Restaurants",
    filterGroup: "food",
    title: "Kurintar Retreat",
    subtitle: "Restaurant",
    location: "Kurintar, Nepal",
    price: "Spent Rs 500",
    numericPrice: 500,
    description: "Your return-trip lunch stop on the Pokhara to Kathmandu route with a road-trip break feel.",
    rating: 4.3,
    tags: ["Highway Stop", "Lunch", "Retreat"],
    ctaPrimary: "Visit",
    image: annapurnaImg,
  },
  {
    id: "food-mugling",
    category: "Cafes & Restaurants",
    filterGroup: "food",
    title: "Mugling Chicken Khana",
    subtitle: "Local Food",
    location: "Mugling, Nepal",
    price: "Spent Rs 350",
    numericPrice: 350,
    description: "A practical road meal stop from the Kathmandu to Pokhara journey and one of the trip's first food spends.",
    rating: 4.2,
    tags: ["Road Stop", "Chicken", "Local Food"],
    ctaPrimary: "Visit",
    image: mustangImg,
  },
];

const busCards: ServiceMarketplaceCard[] = [
  {
    id: "bus-koili",
    category: "Bus Tickets",
    filterGroup: "transport",
    title: "Koili Bus",
    subtitle: "Sunday departure",
    location: "KTM -> Pokhara",
    price: "Rs 1,600",
    numericPrice: 1600,
    description: "Outbound ticket from Kathmandu to Pokhara for the start of your New Year trip.",
    rating: 4.2,
    tags: ["Seat A3", "7:00 AM", "Digital Ticket"],
    ctaPrimary: "Book",
    image: koiliBusImg,
    meta: ["Company: Koili Bus", "Route: KTM -> Pokhara", "Date: Sunday"],
  },
  {
    id: "bus-swift",
    category: "Bus Tickets",
    filterGroup: "transport",
    title: "Swift Holiday Bus",
    subtitle: "Wednesday return",
    location: "Pokhara -> KTM",
    price: "Rs 1,600",
    numericPrice: 1600,
    description: "Return ticket used on the final day of the trip back toward Kathmandu.",
    rating: 4.3,
    tags: ["Seat B1", "8:00 AM", "Holiday Coach"],
    ctaPrimary: "Book",
    image: swiftHolidayBusImg,
    meta: ["Company: Swift Holiday Bus", "Route: Pokhara -> KTM", "Date: Wednesday"],
  },
];

const localTransportCards: ServiceMarketplaceCard[] = [
  {
    id: "ride-begnas-outbound",
    category: "Local Transport",
    filterGroup: "transport",
    title: "InDrive Lakeside -> Begnas",
    subtitle: "Local Ride",
    location: "Pokhara",
    price: "Fare Rs 350",
    numericPrice: 350,
    description: "The outbound local ride from Lakeside to Begnas Lake used on Monday.",
    rating: 4.7,
    tags: ["InDrive", "Lake Route", "Private Ride"],
    ctaPrimary: "Book",
    ctaSecondary: "Open Map",
    image: annapurnaImg,
  },
  {
    id: "ride-begnas-return",
    category: "Local Transport",
    filterGroup: "transport",
    title: "InDrive Begnas -> Lakeside",
    subtitle: "Local Ride",
    location: "Pokhara",
    price: "Fare Rs 350",
    numericPrice: 350,
    description: "The return local ride back to Lakeside after the Begnas day out.",
    rating: 4.7,
    tags: ["InDrive", "Return Trip", "Lakeside"],
    ctaPrimary: "Book",
    ctaSecondary: "Open Map",
    image: langtangImg,
  },
];

const activityCards: ServiceMarketplaceCard[] = [
  {
    id: "activity-kayaking",
    category: "Activities",
    filterGroup: "activities",
    title: "Kayaking",
    subtitle: "Water activity",
    location: "Pokhara",
    price: "Rs 300",
    numericPrice: 300,
    description: "A low-cost activity from your Tuesday itinerary and the clearest direct activity booking candidate from the trip.",
    rating: 4.8,
    tags: ["Outdoor", "Water", "Adventure"],
    ctaPrimary: "Book",
    ctaSecondary: "View Details",
    image: annapurnaImg,
    meta: ["Duration: 1.5 hours"],
  },
  {
    id: "activity-begnas",
    category: "Activities",
    filterGroup: "activities",
    title: "Begnas Lake Visit",
    subtitle: "Scenic stop",
    location: "Begnas Lake, Pokhara",
    price: "Included in day plan",
    numericPrice: 0,
    description: "A scenic itinerary moment derived from your Monday route and the associated transport + cafe stops.",
    rating: 4.7,
    tags: ["Lake View", "Relaxed", "Photo Stop"],
    ctaPrimary: "View Details",
    ctaSecondary: "Visit",
    image: poonhillImg,
    meta: ["Duration: Half day"],
  },
  {
    id: "activity-new-year-eve",
    category: "Activities",
    filterGroup: "activities",
    title: "New Year Eve at Tipsy Tuna",
    subtitle: "Nightlife experience",
    location: "Lakeside, Pokhara",
    price: "Rs 1,250",
    numericPrice: 1250,
    description: "A nightlife activity created from your highest single cafe spend and explicit New Year Eve itinerary note.",
    rating: 4.8,
    tags: ["Party", "Music", "New Year"],
    ctaPrimary: "Book",
    ctaSecondary: "View Details",
    image: mustangImg,
    meta: ["Duration: Evening"],
  },
];

export const buildServiceSections = (): ServiceMarketplaceSectionData[] => [
  {
    id: "hotels",
    title: "Hotels",
    description: `Generated from your stay breakdown in ${trip.tripTitle}.`,
    cards: [hotelFeatured, ...hotelRecommendations],
  },
  {
    id: "food",
    title: "Cafes & Restaurants",
    description: "Generated from your food and cafe expenses across the full trip itinerary.",
    cards: foodCards,
  },
  {
    id: "bus",
    title: "Bus Tickets",
    description: "Rebooking-style ticket history based on your outbound and return bus rides.",
    cards: busCards,
  },
  {
    id: "transport",
    title: "Local Transport",
    description: "Derived from local ride entries in the itinerary.",
    cards: localTransportCards,
  },
  {
    id: "activities",
    title: "Activities",
    description: "Activities inferred from activity expenses and itinerary stops.",
    cards: activityCards,
  },
];

export const buildRecentlyUsedServices = () => [
  hotelFeatured,
  foodCards[1],
  busCards[0],
  activityCards[0],
];
