import type {
  Reel,
  Hotel,
  Cafe,
  Guide,
  Porter,
  PermitTicket,
  NearbyAttraction,
} from "./types";

import everestImg from "@/assets/reels/everest.jpg";
import annapurnaImg from "@/assets/reels/annapurna.jpg";
import langtangImg from "@/assets/reels/langtang.jpg";
import poonhillImg from "@/assets/reels/poonhill.jpg";
import mustangImg from "@/assets/reels/mustang.jpg";

export const reelGradients = [
  "from-stone-800 via-amber-900 to-stone-900",
  "from-slate-800 via-stone-700 to-slate-900",
  "from-amber-800 via-stone-800 to-slate-900",
];

export const reels: Reel[] = [
  {
    id: "r-poonhill",
    title: "Poon Hill Trek under Rs 5200",
    subtitle: "Cheapest budget trek guide",
    place: "Poon Hill",
    duration: "0:39",
    budget: "Rs 5,200",
    season: "Oct-Apr",
    transport: "Bus + Jeep + Trek",
    type: "Budget Reel",
    creator: "giggrow",
    handle: "@giggrow",
    description: "Budget-friendly Poon Hill trek under Rs 5200 including transport, food, and stay with the original short-form video feel.",
    rating: 4.9,
    trips: 56,
    followers: "45.2K",
    bio: "Nepal travel hacks and budget trek guides. Proving you do not need big money to see the mountains.",
    reviews: [],
    socials: { instagram: "@giggrow", youtube: "giggrow" },
    image: poonhillImg,
    video: "/reels/poonhill-budget.mp4",
    map: "/maps/poonhill-map.png",
    mapData: {
      title: "Trip Map",
      summary: "Route map from Kathmandu to Pokhara and then onward to Poon Hill, highlighting the major travel legs for this budget trek.",
      destination: "Poon Hill, Nepal",
      googleMapsUrl:
        "https://www.google.com/maps/dir/Kathmandu/Pokhara/Poon+Hill",
      embedQuery: "Kathmandu Pokhara Poon Hill",
      fallbackImage: "/maps/poonhill-map.png",
      stops: [
        { id: "ph-1", name: "Kathmandu", type: "start", note: "Departure city" },
        { id: "ph-2", name: "Pokhara", type: "stop", note: "Transit and trek prep point" },
        { id: "ph-3", name: "Poon Hill", type: "finish", note: "Sunrise viewpoint" },
      ],
      itineraryPreview: [
        "Bus from Kathmandu to Pokhara",
        "Local transfer and trek preparation in Pokhara",
        "Trek to Poon Hill for sunrise and return",
      ],
    },
  },
  {
    id: "r0",
    title: "Pokhara New Year 2083",
    subtitle: "Lakeside lights, Begnas rides, and food memories",
    place: "Pokhara",
    duration: "4 days",
    budget: "Rs 12,865",
    season: "New Year",
    transport: "Bus + InDrive",
    type: "Travel Story",
    creator: "Mirage Shrestha",
    handle: "@mirage.shrestha",
    description: "A scrapbook-style Pokhara trip with cafes, Begnas Lake, kayaking, and New Year Eve energy.",
    rating: 4.9,
    trips: 18,
    followers: "12.8K",
    bio: "Trip journal maker sharing my own travel stories, budgets, cafe stops, and lake-side memories across Nepal.",
    reviews: [],
    socials: { instagram: "@mirage.shrestha", youtube: "MirageShrestha" },
    image: annapurnaImg,
    video: "/reels/Pokhara New Year 2083.mp4",
    map: "/maps/poonhill-map.jpg",
    mapData: {
      title: "Trip Map",
      summary: "Pokhara New Year route covering Lakeside stays, Begnas side trips, food stops, and the return ride to Kathmandu.",
      destination: "Pokhara, Nepal",
      googleMapsUrl:
        "https://www.google.com/maps/dir/Kathmandu/Pokhara+Lakeside/Begnas+Lake/Kurintar/Kathmandu",
      embedQuery: "Pokhara Lakeside and Begnas Lake trip from Kathmandu",
      fallbackImage: "/maps/poonhill-map.jpg",
      stops: [
        { id: "pk-1", name: "Kathmandu", type: "start", note: "Departure city" },
        { id: "pk-2", name: "Pokhara Lakeside", type: "stop", note: "Main stay area" },
        { id: "pk-3", name: "Begnas Lake", type: "stop", note: "Lake visit and kayaking" },
        { id: "pk-4", name: "Kurintar", type: "stop", note: "Lunch break on return" },
        { id: "pk-5", name: "Kathmandu", type: "finish", note: "Trip wrap-up" },
      ],
      itineraryPreview: [
        "Bus from Kathmandu to Pokhara with food stops",
        "InDrive rides between Lakeside and Begnas Lake",
        "Return bus with Kurintar lunch break",
      ],
    },
  },
  {

    id: "r1",
    title: "Begnas Lake morning reel",
    subtitle: "Soft water, quiet boats, clear weather",
    place: "Begnas Lake",
    duration: "0:34",
    budget: "Rs 350 ride",
    season: "Spring",
    transport: "InDrive",
    type: "Reel",
    creator: "Sarad Jung Thapa",
    handle: "@saradjungthapa",
    description: "A calm lake reel from the Pokhara side trip with a soft sunrise look and reflective water shots.",
    rating: 4.8,
    trips: 24,
    followers: "16.1K",
    bio: "Adventure filmmaker focused on lakes, highways, and quick-turn travel reels from around Nepal.",
    reviews: [],
    socials: { instagram: "@saradjungthapa", youtube: "SaradJungThapa" },
    image: annapurnaImg,
    map: "/maps/poonhill-map.jpg",
    mapData: {
      title: "Trip Map",
      summary: "A short local route focused on the calm ride from Lakeside to Begnas and back.",
      destination: "Begnas Lake, Nepal",
      googleMapsUrl: "https://www.google.com/maps/dir/Pokhara+Lakeside/Begnas+Lake",
      embedQuery: "Begnas Lake from Pokhara Lakeside",
      fallbackImage: "/maps/poonhill-map.jpg",
      stops: [
        { id: "bg-1", name: "Pokhara Lakeside", type: "start", note: "Pickup point" },
        { id: "bg-2", name: "Begnas Lake", type: "finish", note: "Lakefront reel stop" },
      ],
      itineraryPreview: ["Morning InDrive ride", "Lakefront stop and reel capture"],
    },
  },
  {
    id: "r2",
    title: "Mustang ride dust trail",
    subtitle: "Road trip clips across dry mountain roads",
    place: "Mustang",
    duration: "0:28",
    budget: "Rs 18,900",
    season: "Winter",
    transport: "Jeep",
    type: "Adventure",
    creator: "Amrit Thapa",
    handle: "@amritthapa",
    description: "Quick-cut road diary clips from Mustang with high-desert color, jeep windows, and village stops.",
    rating: 4.7,
    trips: 20,
    followers: "11.7K",
    bio: "Road-trip storyteller capturing mountain highways, desert trails, and adventure edits from Nepal.",
    reviews: [],
    socials: { instagram: "@amritthapa", youtube: "AmritThapa" },
    image: mustangImg,
    map: "/maps/jomsom-map.jpg",
    mapData: {
      title: "Trip Map",
      summary: "A road-trip route through Mustang with long jeep segments and mountain village stops.",
      destination: "Mustang, Nepal",
      googleMapsUrl: "https://www.google.com/maps/dir/Pokhara/Jomsom/Kagbeni/Mustang",
      embedQuery: "Mustang road trip from Pokhara to Jomsom to Kagbeni",
      fallbackImage: "/maps/jomsom-map.jpg",
      stops: [
        { id: "ms-1", name: "Pokhara", type: "start" },
        { id: "ms-2", name: "Jomsom", type: "stop" },
        { id: "ms-3", name: "Kagbeni", type: "stop" },
        { id: "ms-4", name: "Mustang", type: "finish" },
      ],
      itineraryPreview: ["Jeep transfer into Mustang", "Village stops for reel shots"],
    },
  },
  {
    id: "r3",
    title: "Langtang bakery stop",
    subtitle: "Warm tea, cold air, and trail notes",
    place: "Langtang",
    duration: "0:26",
    budget: "Rs 15,200",
    season: "Winter",
    transport: "Trek",
    type: "Mountain Reel",
    creator: "Sarad Jung Thapa",
    handle: "@saradjungthapa",
    description: "A small trail memory focused on bakery warmth, prayer flags, and snow-edged ridge views.",
    rating: 4.8,
    trips: 24,
    followers: "16.1K",
    bio: "Adventure filmmaker focused on lakes, highways, and quick-turn travel reels from around Nepal.",
    reviews: [],
    socials: { instagram: "@saradjungthapa", youtube: "SaradJungThapa" },
    image: langtangImg,
    mapData: {
      title: "Trip Map",
      summary: "A mountain route through Langtang with tea-house pauses and trail-side bakery memories.",
      destination: "Langtang, Nepal",
      googleMapsUrl: "https://www.google.com/maps/dir/Kathmandu/Syabrubesi/Langtang+Village/Kyanjin+Gompa",
      embedQuery: "Langtang trekking route from Syabrubesi to Kyanjin Gompa",
      stops: [
        { id: "lg-1", name: "Kathmandu", type: "start" },
        { id: "lg-2", name: "Syabrubesi", type: "stop" },
        { id: "lg-3", name: "Langtang Village", type: "stop" },
        { id: "lg-4", name: "Kyanjin Gompa", type: "finish" },
      ],
      itineraryPreview: ["Road transfer to Syabrubesi", "Trail climb with bakery stop"],
    },
  },
  {
    id: "r4",
    title: "Annapurna sunrise frames",
    subtitle: "Early light from the base camp trail",
    place: "Annapurna",
    duration: "0:31",
    budget: "Rs 24,500",
    season: "Spring",
    transport: "Trek",
    type: "Cinematic",
    creator: "Amrit Thapa",
    handle: "@amritthapa",
    description: "A travel-focused short with sunrise color, layered peaks, and diary text overlays from Annapurna.",
    rating: 5,
    trips: 20,
    followers: "11.7K",
    bio: "Road-trip storyteller capturing mountain highways, desert trails, and adventure edits from Nepal.",
    reviews: [],
    socials: { instagram: "@amritthapa", youtube: "AmritThapa" },
    image: everestImg,
    mapData: {
      title: "Trip Map",
      summary: "Annapurna route progression shaped around sunrise frames and layered ridge views.",
      destination: "Annapurna Region, Nepal",
      googleMapsUrl: "https://www.google.com/maps/dir/Pokhara/Ghandruk/Chhomrong/Annapurna+Base+Camp",
      embedQuery: "Annapurna Base Camp route from Pokhara to Ghandruk to Chhomrong",
      stops: [
        { id: "ab-1", name: "Pokhara", type: "start" },
        { id: "ab-2", name: "Ghandruk", type: "stop" },
        { id: "ab-3", name: "Chhomrong", type: "stop" },
        { id: "ab-4", name: "Annapurna Base Camp", type: "finish" },
      ],
      itineraryPreview: ["Trail transfer from Pokhara", "Multi-day ascent to base camp"],
    },
  },
];

export const hotels: Hotel[] = [
  { id: "h1p", name: "Pokhara Lakeside Inn", area: "Pokhara", price: "Rs 3,000/night", tag: "Comfort", phone: "+977-61-462555", rating: 4.7, amenities: ["Lake View", "WiFi", "AC", "Restaurant"] },
  { id: "h2p", name: "Hotel Middle Path", area: "Pokhara", price: "Rs 1,800/night", tag: "Budget", phone: "+977-61-462666", rating: 4.3, amenities: ["WiFi", "Hot Water", "Garden"] },
  { id: "h3p", name: "Fish Tail Lodge", area: "Pokhara", price: "Rs 8,000/night", tag: "Premium", phone: "+977-61-462777", rating: 4.9, amenities: ["Lake View", "Spa", "Restaurant", "Bar"] },
  { id: "h1j", name: "Jomsom Eco Lodge", area: "Jomsom", price: "Rs 2,000/night", tag: "Budget", phone: "+977-69-440123", rating: 4.3, amenities: ["WiFi", "Hot Water", "Restaurant"] },
  { id: "h1a", name: "Marpha Apple Stay", area: "Marpha", price: "Rs 3,500/night", tag: "Scenic", phone: "+977-69-440456", rating: 4.6, amenities: ["Garden", "Hot Water", "Mountain View"] },
  { id: "h1g", name: "Kagbeni Heritage House", area: "Kagbeni", price: "Rs 2,500/night", tag: "Heritage", phone: "+977-69-440321", rating: 4.4, amenities: ["Rooftop", "Hot Water", "WiFi"] },
];

export const cafes: Cafe[] = [
  { id: "c1p", name: "Lakeside Brew", area: "Pokhara", price: "Rs 250-600", specialty: "Craft Coffee & Pastries", rating: 4.7, openHours: "6:30 AM - 9 PM" },
  { id: "c2p", name: "Busy Bee Cafe", area: "Pokhara", price: "Rs 200-500", specialty: "Pancakes & Smoothies", rating: 4.4, openHours: "7 AM - 8 PM" },
  { id: "c3p", name: "French Creperie", area: "Pokhara", price: "Rs 350-800", specialty: "Crepes & Coffee", rating: 4.6, openHours: "8 AM - 9 PM" },
  { id: "c1a", name: "Apple Pie Corner", area: "Marpha", price: "Rs 300-700", specialty: "Apple Pie & Cider", rating: 4.8, openHours: "7 AM - 8 PM" },
  { id: "c1g", name: "Kagbeni Coffee House", area: "Kagbeni", price: "Rs 200-500", specialty: "Espresso & Pancakes", rating: 4.6, openHours: "7 AM - 8 PM" },
];

export const guides: Guide[] = [
  { id: "g1", name: "Pemba Sherpa", experience: "12 years", region: "Everest, Annapurna", languages: "Nepali, English, Hindi", rating: 4.9, treks: 340, badge: "Senior Guide", price: "Rs 3,000/day", phone: "+977-98XXXXXXXX" },
  { id: "g2", name: "Lakpa Tamang", experience: "8 years", region: "Langtang, Manaslu", languages: "Nepali, English", rating: 4.7, treks: 180, badge: "Certified Guide", price: "Rs 2,500/day", phone: "+977-98XXXXXXXX" },
  { id: "g3", name: "Dawa Dorje", experience: "15 years", region: "All major routes", languages: "Nepali, English, Japanese", rating: 5, treks: 500, badge: "Master Guide", price: "Rs 4,000/day", phone: "+977-98XXXXXXXX" },
];

export const porters: Porter[] = [
  { id: "pt1", name: "Mingma Rai", experience: "6 years", capacity: "25 kg", region: "Everest", rating: 4.8, price: "Rs 1,500/day", phone: "+977-98XXXXXXXX" },
  { id: "pt2", name: "Nima Lama", experience: "4 years", capacity: "20 kg", region: "Annapurna", rating: 4.6, price: "Rs 1,200/day", phone: "+977-98XXXXXXXX" },
  { id: "pt3", name: "Karma Bhote", experience: "10 years", capacity: "30 kg", region: "All routes", rating: 4.9, price: "Rs 1,800/day", phone: "+977-98XXXXXXXX" },
];

export const tickets: PermitTicket[] = [
  { id: "t1", name: "TIMS Card", type: "Permit", price: "Rs 2,000", desc: "Trekkers' Information Management System permit", required: true },
  { id: "t2", name: "Annapurna Conservation Area", type: "Entry Permit", price: "Rs 3,000", desc: "Required for Annapurna region treks", required: true },
  { id: "t3", name: "Langtang National Park", type: "Entry Permit", price: "Rs 3,000", desc: "Required for Langtang treks", required: true },
  { id: "t4", name: "Upper Mustang Restricted Permit", type: "Special Permit", price: "USD 500 (10 days)", desc: "Restricted permit for Mustang routes", required: false },
];

export const nearbyAttractions: NearbyAttraction[] = [
  { id: "a1", name: "Begnas Lake", area: "Pokhara", type: "Lake", price: "Free" },
  { id: "a2", name: "Phewa Lakeside", area: "Pokhara", type: "Lifestyle", price: "Free" },
  { id: "a3", name: "Muktinath Temple", area: "Mustang", type: "Spiritual", price: "Free" },
  { id: "a4", name: "Kagbeni Old Town", area: "Mustang", type: "Heritage", price: "Free" },
  { id: "a5", name: "Kyanjin Gompa", area: "Langtang", type: "Cultural", price: "Free" },
];
