import annapurnaImg from "@/assets/reels/annapurna.jpg";
import everestImg from "@/assets/reels/everest.jpg";
import langtangImg from "@/assets/reels/langtang.jpg";
import mustangImg from "@/assets/reels/mustang.jpg";
import poonhillImg from "@/assets/reels/poonhill.jpg";

import type { MyTrekStore } from "@/components/my-trek/types";

export const MY_TREK_STORAGE_KEY = "true-nepal-my-trek-profile";

export const getDefaultMyTrekStore = (): MyTrekStore => ({
  profile: {
    name: "Mirage Shrestha",
    handle: "@mirage.shrestha",
    bio: "I use this space as my trip journal for uploads, budgets, lakeside cafe stops, and unfinished travel drafts from around Nepal.",
    location: "Kathmandu, Nepal",
  },
  treks: [
    {
      id: "trek-pokhara",
      ownerHandle: "@mirage.shrestha",
      title: "Pokhara New Year 2083",
      destination: "Pokhara, Nepal",
      date: "Apr 13 - Apr 16, 2026",
      budgetLabel: "Rs 12,865",
      budgetValue: 12865,
      description: "New Year lakeside memories with Begnas, cafes, kayaking, and a clean budget breakdown.",
      status: "Published",
      coverImage: poonhillImg,
    },
    {
      id: "trek-annapurna",
      ownerHandle: "@amritthapa",
      title: "Annapurna Base Camp",
      destination: "Annapurna Region, Nepal",
      date: "Mar 08 - Mar 15, 2026",
      budgetLabel: "Rs 24,500",
      budgetValue: 24500,
      description: "Sunrise ridgelines, teahouse meals, and a week of mountain diary updates from the ABC trail.",
      status: "Published",
      coverImage: annapurnaImg,
    },
    {
      id: "trek-mustang",
      ownerHandle: "@amritthapa",
      title: "Mustang Ride",
      destination: "Upper Mustang, Nepal",
      date: "Feb 02 - Feb 07, 2026",
      budgetLabel: "Rs 18,900",
      budgetValue: 18900,
      description: "Dusty roads, desert light, and a photo-heavy road journal through Mustang villages.",
      status: "Published",
      coverImage: mustangImg,
    },
    {
      id: "trek-langtang",
      ownerHandle: "@saradjungthapa",
      title: "Langtang Trek",
      destination: "Langtang Valley, Nepal",
      date: "Jan 17 - Jan 22, 2026",
      budgetLabel: "Rs 15,200",
      budgetValue: 15200,
      description: "A short alpine reset with Tamang culture stops, bakery breaks, and snow-edged trails.",
      status: "Draft",
      coverImage: langtangImg,
    },
  ],
  reels: [
    {
      id: "reel-begnas",
      ownerHandle: "@saradjungthapa",
      title: "Begnas Lake morning ride",
      duration: "0:34",
      engagement: "12.4K views",
      status: "Published",
      thumbnail: annapurnaImg,
    },
    {
      id: "reel-lakeside",
      ownerHandle: "@mirage.shrestha",
      title: "Lakeside cafe crawl",
      duration: "0:22",
      engagement: "8.9K views",
      status: "Published",
      thumbnail: poonhillImg,
    },
    {
      id: "reel-new-year",
      ownerHandle: "@mirage.shrestha",
      title: "New Year Eve at Tipsy Tuna",
      duration: "0:41",
      engagement: "15.1K views",
      status: "Published",
      thumbnail: everestImg,
    },
    {
      id: "reel-mustang",
      ownerHandle: "@amritthapa",
      title: "Mustang road dust reel",
      duration: "0:28",
      engagement: "Draft clip",
      status: "Draft",
      thumbnail: mustangImg,
    },
  ],
  stories: [
    {
      id: "story-pokhara",
      ownerHandle: "@mirage.shrestha",
      title: "Pokhara food, ferries, and late-night lights",
      date: "Apr 16, 2026",
      preview: "A scrapbook-style journal entry from Begnas, Lakeside, and the New Year countdown.",
      status: "Published",
      coverImage: poonhillImg,
    },
    {
      id: "story-abc",
      ownerHandle: "@amritthapa",
      title: "Annapurna Base Camp photo journal",
      date: "Mar 15, 2026",
      preview: "Cold starts, teahouse windows, and the final approach into base camp.",
      status: "Published",
      coverImage: annapurnaImg,
    },
    {
      id: "story-langtang",
      ownerHandle: "@saradjungthapa",
      title: "Langtang bakery stop notes",
      date: "Jan 22, 2026",
      preview: "Soft snow, bakery warmth, and a trail diary written between climbs.",
      status: "Published",
      coverImage: langtangImg,
    },
  ],
  drafts: [
    {
      id: "draft-pokhara-story",
      ownerHandle: "@mirage.shrestha",
      title: "Pokhara Story Draft",
      kind: "story",
      updatedAt: "Edited 2 hours ago",
      description: "Still needs final captions and two more gallery shots from Lakeside.",
      coverImage: poonhillImg,
    },
    {
      id: "draft-langtang-reel",
      ownerHandle: "@saradjungthapa",
      title: "Langtang Reel Draft",
      kind: "reel",
      updatedAt: "Edited yesterday",
      description: "Trim the opening clip and add the ridge sunrise beat drop.",
      coverImage: langtangImg,
    },
    {
      id: "draft-mustang-budget",
      ownerHandle: "@amritthapa",
      title: "Mustang Budget Draft",
      kind: "trek",
      updatedAt: "Edited 3 days ago",
      description: "Transport and stay totals are ready, but the food notes still need cleanup.",
      coverImage: mustangImg,
    },
  ],
});

export const creatorProfileStores: Record<string, MyTrekStore> = {
  "@mirage.shrestha": {
    profile: {
      name: "Mirage Shrestha",
      handle: "@mirage.shrestha",
      bio: "I use this space as my trip journal for uploads, budgets, lakeside cafe stops, and unfinished travel drafts from around Nepal.",
      location: "Kathmandu, Nepal",
    },
    treks: [
      {
        id: "trek-pokhara",
        ownerHandle: "@mirage.shrestha",
        title: "Pokhara New Year 2083",
        destination: "Pokhara, Nepal",
        date: "Apr 13 - Apr 16, 2026",
        budgetLabel: "Rs 12,865",
        budgetValue: 12865,
        description: "New Year lakeside memories with Begnas, cafes, kayaking, and a clean budget breakdown.",
        status: "Published",
        coverImage: poonhillImg,
      },
    ],
    reels: [
      {
        id: "reel-pokhara-newyear",
        ownerHandle: "@mirage.shrestha",
        title: "Pokhara New Year 2083",
        duration: "4:00",
        engagement: "12.8K views",
        status: "Published",
        thumbnail: annapurnaImg,
      },
      {
        id: "reel-lakeside",
        ownerHandle: "@mirage.shrestha",
        title: "Lakeside cafe crawl",
        duration: "0:22",
        engagement: "8.9K views",
        status: "Published",
        thumbnail: poonhillImg,
      },
      {
        id: "reel-new-year",
        ownerHandle: "@mirage.shrestha",
        title: "New Year Eve at Tipsy Tuna",
        duration: "0:41",
        engagement: "15.1K views",
        status: "Published",
        thumbnail: everestImg,
      },
    ],
    stories: [
      {
        id: "story-pokhara",
        ownerHandle: "@mirage.shrestha",
        title: "Pokhara food, ferries, and late-night lights",
        date: "Apr 16, 2026",
        preview: "A scrapbook-style journal entry from Begnas, Lakeside, and the New Year countdown.",
        status: "Published",
        coverImage: poonhillImg,
      },
    ],
    drafts: [
      {
        id: "draft-pokhara-story",
        ownerHandle: "@mirage.shrestha",
        title: "Pokhara Story Draft",
        kind: "story",
        updatedAt: "Edited 2 hours ago",
        description: "Still needs final captions and two more gallery shots from Lakeside.",
        coverImage: poonhillImg,
      },
    ],
  },

  "@giggrow": {
    profile: {
      name: "giggrow",
      handle: "@giggrow",
      bio: "Nepal budget trek creator sharing practical route costs, transport hacks, and low-cost mountain plans that still feel cinematic.",
      location: "Pokhara, Nepal",
    },
    treks: [
      {
        id: "trek-poonhill",
        ownerHandle: "@giggrow",
        title: "Poon Hill Trek under Rs 5200",
        destination: "Poon Hill, Nepal",
        date: "3 day budget route",
        budgetLabel: "Rs 5,200",
        budgetValue: 5200,
        description: "The original low-budget Poon Hill plan with bus, jeep, food, and stay mapped into one clean budget trek.",
        status: "Published",
        coverImage: poonhillImg,
      },
    ],
    reels: [
      {
        id: "reel-poonhill-budget",
        ownerHandle: "@giggrow",
        title: "Poon Hill budget reel",
        duration: "0:39",
        engagement: "45.2K views",
        status: "Published",
        thumbnail: poonhillImg,
      },
    ],
    stories: [
      {
        id: "story-poonhill-guide",
        ownerHandle: "@giggrow",
        title: "How I kept Poon Hill under budget",
        date: "Apr 10, 2026",
        preview: "A creator-style breakdown of the transport, stay, and meal choices that kept the whole Poon Hill trek close to Rs 5200.",
        status: "Published",
        coverImage: poonhillImg,
      },
    ],
    drafts: [],
  },
  "@saradjungthapa": {
    profile: {
      name: "Sarad Jung Thapa",
      handle: "@saradjungthapa",
      bio: "I shoot calm mountain reels, quiet lake mornings, and trail-side edits that feel like a slow travel diary.",
      location: "Kathmandu, Nepal",
    },
    treks: [
      {
        id: "trek-langtang-public",
        ownerHandle: "@saradjungthapa",
        title: "Langtang Trek",
        destination: "Langtang Valley, Nepal",
        date: "Jan 17 - Jan 22, 2026",
        budgetLabel: "Rs 15,200",
        budgetValue: 15200,
        description: "Snow-edged trails, tea-house pauses, and bakery-stop memories from a compact Langtang plan.",
        status: "Published",
        coverImage: langtangImg,
      },
    ],
    reels: [
      {
        id: "reel-begnas-public",
        ownerHandle: "@saradjungthapa",
        title: "Begnas Lake morning reel",
        duration: "0:34",
        engagement: "16.1K views",
        status: "Published",
        thumbnail: annapurnaImg,
      },
      {
        id: "reel-langtang-public",
        ownerHandle: "@saradjungthapa",
        title: "Langtang bakery stop",
        duration: "0:26",
        engagement: "9.8K views",
        status: "Published",
        thumbnail: langtangImg,
      },
    ],
    stories: [
      {
        id: "story-langtang-public",
        ownerHandle: "@saradjungthapa",
        title: "Langtang bakery stop notes",
        date: "Jan 22, 2026",
        preview: "Warm bakery windows, thin mountain air, and small trail notes from a winter Langtang run.",
        status: "Published",
        coverImage: langtangImg,
      },
    ],
    drafts: [
      {
        id: "draft-sarad-lake-cut",
        ownerHandle: "@saradjungthapa",
        title: "Begnas Sound Design Draft",
        kind: "reel",
        updatedAt: "Edited yesterday",
        description: "Need to rebalance the lake audio and trim the opening two seconds.",
        coverImage: annapurnaImg,
      },
    ],
  },
  "@amritthapa": {
    profile: {
      name: "Amrit Thapa",
      handle: "@amritthapa",
      bio: "Road-trip editor sharing dusty jeep routes, sunrise trail clips, and rugged mountain journals from around Nepal.",
      location: "Pokhara, Nepal",
    },
    treks: [
      {
        id: "trek-mustang-public",
        ownerHandle: "@amritthapa",
        title: "Mustang Ride",
        destination: "Upper Mustang, Nepal",
        date: "Feb 02 - Feb 07, 2026",
        budgetLabel: "Rs 18,900",
        budgetValue: 18900,
        description: "A dry mountain road journal built around jeep routes, village stops, and wind-swept desert light.",
        status: "Published",
        coverImage: mustangImg,
      },
      {
        id: "trek-annapurna-public",
        ownerHandle: "@amritthapa",
        title: "Annapurna Base Camp",
        destination: "Annapurna Region, Nepal",
        date: "Mar 08 - Mar 15, 2026",
        budgetLabel: "Rs 24,500",
        budgetValue: 24500,
        description: "A week of mountain mornings, tea-house stays, and ridge-light footage from the ABC trail.",
        status: "Published",
        coverImage: annapurnaImg,
      },
    ],
    reels: [
      {
        id: "reel-mustang-public",
        ownerHandle: "@amritthapa",
        title: "Mustang ride dust trail",
        duration: "0:28",
        engagement: "11.7K views",
        status: "Published",
        thumbnail: mustangImg,
      },
      {
        id: "reel-annapurna-public",
        ownerHandle: "@amritthapa",
        title: "Annapurna sunrise frames",
        duration: "0:31",
        engagement: "13.4K views",
        status: "Published",
        thumbnail: everestImg,
      },
    ],
    stories: [
      {
        id: "story-abc-public",
        ownerHandle: "@amritthapa",
        title: "Annapurna Base Camp photo journal",
        date: "Mar 15, 2026",
        preview: "Layered peaks, sunrise color, and quiet trail moments from the Annapurna route.",
        status: "Published",
        coverImage: annapurnaImg,
      },
    ],
    drafts: [
      {
        id: "draft-amrit-mustang",
        ownerHandle: "@amritthapa",
        title: "Mustang Budget Draft",
        kind: "trek",
        updatedAt: "Edited 3 days ago",
        description: "Transport and stay totals are ready, but the food notes still need cleanup.",
        coverImage: mustangImg,
      },
    ],
  },
};
